# Generated by Django 3.0.5 on 2020-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=80)),
                ('server_addr', models.CharField(max_length=80)),
                ('is_file', models.BooleanField()),
                ('size', models.BigIntegerField()),
                ('acc_time', models.BigIntegerField()),
                ('mod_time', models.BigIntegerField()),
                ('root_dir_path', models.CharField(max_length=80, null=True)),
                ('dir_path', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=1000)),
                ('extension', models.CharField(max_length=20)),
                ('rec_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('exists', models.BooleanField(default=True)),
                ('exists_check_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
