# Generated by Django 3.0.5 on 2020-04-06 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ep_analyze', '0002_filestattest'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestattest',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filestattest',
            name='exists_check_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filestattest',
            name='rec_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 6, 14, 46, 22, 934800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filestattest',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
