# Generated by Django 3.0.4 on 2020-04-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='dir',
            new_name='directory',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='name',
            new_name='file_name',
        ),
    ]
