# Generated by Django 3.0.5 on 2020-04-17 21:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_analyze', '0004_auto_20200417_2155'),
        ('ep_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('google_isbn_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('files', models.ManyToManyField(to='ep_analyze.FileStat')),
            ],
        ),
        migrations.CreateModel(
            name='FileContentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_method', models.CharField(max_length=50)),
                ('pages_inspected', models.CharField(max_length=1000)),
                ('pages_dimensions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dimension_unit', models.CharField(max_length=20)),
                ('isbn_like', models.CharField(max_length=20)),
                ('pages_with_isbn', models.CharField(max_length=50)),
                ('page_chars', django.contrib.postgres.fields.jsonb.JSONField()),
                ('page_images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doc_pagecount', models.IntegerField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep_analyze.FileStat')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
