# Generated by Django 3.0.5 on 2020-04-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep_books', '0002_auto_20200401_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_name',
        ),
    ]
