from django.db import models

# Table with files statistics
class FilesStat(models.Model):
    """
    Maps file generated by linux command:
    $ find . -exec stat -c "%F %s %X %Y %n" {} \; > file
    """
    # can be f or d (file or directory) %F  file type
    file_type = models.CharField(max_length=1)
    # %s total size, in bytes
    size = models.IntegerField()
    # %X time of last access, seconds since Epoch
    acc_time = models.IntegerField()
    # %Y time of last data modification, seconds since Epoch
    mod_time = models.IntegerField()
    # root dir path, such as /mnt/g/wrapper
    root_dir_path = models.CharField(max_length=200)
    # directory path; begins with / end ends with dir_name
    dir_path = models.CharField(max_length=1000)
    # file name with extension (suffix)
    file_name = models.CharField(max_length=1000)
    # only extension (suffix)
    extension = models.CharField(max_length=20)
    # time of record in db (timestamp)
    rec_timestamp = models.DateTimeField(auto_now_add=True)
    # time of update (with Model.save())
    update_time = models.DateTimeField(auto_now=True)



    
